In [4]:
import numpy as np 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC, SVR
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [5]:
#Step 1.
data = pd.read_csv("train.csv")
data.head()

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0   1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1   2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2   4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3   5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4   7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     18.7  394.63   2.94  33.4  
3     18.7  396.90   5.33  36.2  
4     15.2  395.60  12.43  22.9

# Training and Test split. 

In [3]:
#step2.
data = data.drop(columns=['ID']) # Data Drop. 

In [4]:
#step3.
data.describe()

crim          zn       indus        chas         nox          rm  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean     3.360341   10.689189   11.293483    0.060060    0.557144    6.265619   
std      7.352272   22.674762    6.998123    0.237956    0.114955    0.703952   
min      0.006320    0.000000    0.740000    0.000000    0.385000    3.561000   
25%      0.078960    0.000000    5.130000    0.000000    0.453000    5.884000   
50%      0.261690    0.000000    9.900000    0.000000    0.538000    6.202000   
75%      3.678220   12.500000   18.100000    0.000000    0.631000    6.595000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.725000   

              age         dis         rad         tax     ptratio       black  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean    68.226426    3.709934    9.633634  409.279279   18.448048  359.466096   
std     28.133344    1.981123    8.742174  170.841988    2.151821   86.584567   
min      6.000000    1.129600    1.000000  188.000000   12.600000    3.500000   
25%     45.400000    2.122400    4.000000  279.000000   17.400000  376.730000   
50%     76.700000    3.092300    5.000000  330.000000   19.000000  392.050000   
75%     93.800000    5.116700   24.000000  666.000000   20.200000  396.240000   
max    100.000000   10.710300   24.000000  711.000000   21.200000  396.900000   

            lstat        medv  
count  333.000000  333.000000  
mean    12.515435   22.768769  
std      7.067781    9.173468  
min      1.730000    5.000000  
25%      7.180000   17.400000  
50%     10.970000   21.600000  
75%     16.420000   25.000000  
max     37.970000   50.000000

In [6]:
# step 4
data.info()
data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 15 columns):
ID         333 non-null int64
crim       333 non-null float64
zn         333 non-null float64
indus      333 non-null float64
chas       333 non-null int64
nox        333 non-null float64
rm         333 non-null float64
age        333 non-null float64
dis        333 non-null float64
rad        333 non-null int64
tax        333 non-null int64
ptratio    333 non-null float64
black      333 non-null float64
lstat      333 non-null float64
medv       333 non-null float64
dtypes: float64(11), int64(4)
memory usage: 39.1 KB


(333, 15)

In [7]:
#step5.
y = data["medv"].values
x = data.iloc[:,:-1].values

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(266, 14) (266,)
(67, 14) (67,)


In [9]:
#step6.
clf = LinearRegression()
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
#step7.
y_train_pred=clf.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print("Training metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Training metrics: 
Mean square error:  21.15587907662772 
Mean absolute error:  3.1772573187623796 
R2 score 0.7371221935252688


In [11]:
#step8.
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  28.736004275128654 
Mean absolute error:  3.7765987142060826 
R2 score 0.7034471355489141


In [11]:
#step9.
clf2 = SVR()
clf2.fit(X_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [12]:
#step10.
y_train_pred=clf2.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print("Training metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Training metrics: 
Mean square error:  59.92892149365455 
Mean absolute error:  4.926947961084357 
R2 score 0.1599908044383359


In [13]:
#step11.
y_test_pred=clf2.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  141.1707976759101 
Mean absolute error:  8.586232357818172 
R2 score -0.14304742410387616


### polynomial model

In [14]:
#step5.
y = data["medv"].values
x = data.iloc[:,:-1].values

pf = PolynomialFeatures(2)
x = pf.fit_transform(x)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(266, 105) (266,)
(67, 105) (67,)


In [16]:
#step6.
clf = LinearRegression()
clf.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
#step7.
y_train_pred=clf.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print("Training metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Training metrics: 
Mean square error:  3.9338888445805607 
Mean absolute error:  1.540309925276534 
R2 score 0.9551067764650117


In [21]:
#step8.
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  25.898703818640076 
Mean absolute error:  3.4403292620359966 
R2 score 0.6033165431335181


In [22]:
clf = SVR()
clf.fit(X_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [23]:
#step7.
y_train_pred=clf.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print("Training metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

#step8.
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Training metrics: 
Mean square error:  77.24473596529853 
Mean absolute error:  5.740597098214285 
R2 score 0.1184892772533237
Test metrics: 
Mean square error:  65.89044776119403 
Mean absolute error:  5.832835820895522 
R2 score -0.009226205891382788


bias and variance <br>
bias variance tradeoff

# 5/9/2019

# Adult Data

In [14]:
columns = ['age','workClass','fnlwgt','education','education-num','marital-status',
 'occupation','relationship','race','sex','capital-gain','capital-loss',
 'hours-per-week','native-country','income']
data = pd.read_csv("adultdata.csv", names=columns)
data.head()

age          workClass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workClass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [16]:
workClassle = LabelEncoder()
workClassint = workClassle.fit_transform(data.workClass)

In [17]:
workClassint

array([7, 6, 4, ..., 4, 4, 5], dtype=int64)

In [18]:
educationle = LabelEncoder()
educationint = educationle.fit_transform(data.education)

In [19]:
educationint

array([ 9,  9, 11, ..., 11, 11, 11], dtype=int64)

In [20]:
marital_statusle = LabelEncoder()
marital_statusint = marital_statusle.fit_transform(data["marital-status"])                                   

In [21]:
marital_statusint

array([4, 2, 0, ..., 6, 4, 2], dtype=int64)

In [22]:
occupationle = LabelEncoder()
occupationint = occupationle.fit_transform(data.occupation)

In [23]:
occupationint

array([1, 4, 6, ..., 1, 1, 4], dtype=int64)

In [24]:
relationshiple = LabelEncoder()
relationshipint = relationshiple.fit_transform(data.relationship)

In [25]:
relationshipint

array([1, 0, 1, ..., 4, 3, 5], dtype=int64)

In [26]:
racele = LabelEncoder()
raceint = racele.fit_transform(data.race)

In [27]:
raceint 

array([4, 4, 4, ..., 4, 4, 4], dtype=int64)

In [28]:
sexle = LabelEncoder()
sexint = sexle.fit_transform(data.sex)

In [29]:
sexint

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [30]:
native_countryle = LabelEncoder()
native_countryint = native_countryle.fit_transform(data["native-country"])

In [31]:
native_countryint 

array([39, 39, 39, ..., 39, 39, 39], dtype=int64)

In [32]:
incomele = LabelEncoder()
incomeint = incomele.fit_transform(data.income)

In [33]:
data["workClass_int"] = workClassle.transform(data.workClass)
data["education_int"] = educationle.transform(data.education)
data["marital_status_int"] = marital_statusle.transform(data["marital-status"])
data["occupation_int"] = occupationle.transform(data.occupation)
data["relationship_int"] = relationshiple.transform(data.relationship)
data["race_int"] = racele.transform(data.race)
data["sex_int"] = sexle.transform(data.sex)
data["native_country_int"] = native_countryle.transform(data["native-country"])
data["income_int"] = incomele.transform(data.income)

In [34]:
data.head()

age          workClass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

      ...      income  workClass_int  education_int marital_status_int  \
0     ...       <=50K              7              9                  4   
1     ...       <=50K              6              9                  2   
2     ...       <=50K              4             11                  0   
3     ...       <=50K              4              1                  2   
4     ...       <=50K              4              9                  2   

  occupation_int  relationship_int  race_int  sex_int  native_country_int  \
0              1                 1         4        1                  39   
1              4                 0         4        1                  39   
2              6                 1         4        1                  39   
3              6                 0         2        1                  39   
4             10                 5         2        0                   5   

   income_int  
0           0  
1           0  
2           0  
3           0  
4           0  

[5 rows x 24 columns]

In [171]:
X = data[['age','workClass_int','fnlwgt','education_int','education-num','marital_status_int',
 'occupation_int','relationship_int','race_int','sex_int','capital-gain','capital-loss',
 'hours-per-week','native_country_int']].values
Y = data["income_int"].values

In [175]:
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  18.54078769310793 
Mean absolute error:  3.238614187150299 
R2 score 0.608695806107189


In [187]:
clf = SVC()
clf.fit(X_test,y_test)

ValueError: Unknown label type: 'continuous'

In [183]:
y_test_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_test_pred)
print("Accuracy score: ", acc)

ValueError: continuous is not supported

In [167]:
y_test_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_test_pred)
print("Accuracy score: ", acc)

ValueError: continuous is not supported